Sample code for Node and Go
hyperledger/fabric-gateway pull request #71
Opened 2021-03-26 17:21 UTC by andrew-coleman

Very basic samples demonstrating how to write a client application using the gateway SDKs
Go and Node for now.

Signed-off-by: andrew-coleman <andrew_coleman@uk.ibm.com>

2021-03-26 18:10 UTC, bestbeforetoday requested changes
Nice simple examples 👍 

In fine Fabric tradition, I've made a load of comments that I think are worth addressing as they are going to be end user samples so we want the code to look nice. Nothing is a show-stopper though.

2021-03-26 18:10 UTC, bestbeforetoday commented on samples/node/src/sample.ts
> +    }
I think I'd ditch this `catch` block and invoke the `main()` function with `main().catch(console.error);` so anything thrown gets logged to stderr

2021-03-29 09:40 UTC, andrew-coleman commented on Makefile
> +sample-network:: vendor-chaincode
oops, typo

2021-03-29 10:04 UTC, jt-nti approved these changes

2021-03-29 10:12 UTC, merged